# Generated by Django 4.1 on 2025-01-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('AdminApp', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=25)),
                ('tool_photo', models.ImageField(upload_to='')),
                ('tool_price', models.FloatField()),
                ('tool_discription', models.CharField(max_length=100)),
                ('tool_stock', models.IntegerField()),
                ('tool_status', models.CharField(max_length=25)),
                ('tool_type', models.CharField(max_length=25)),
                ('tool_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
                ('tool_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_seller')),
            ],
        ),
    ]
