# Generated by Django 4.1 on 2025-01-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_tbl_subcategory'),
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tool',
            name='tool_category',
        ),
        migrations.AddField(
            model_name='tbl_tool',
            name='tool_subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_subcategory'),
        ),
    ]
