# Generated by Django 4.1 on 2025-01-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=40)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
