# Generated by Django 4.1 on 2025-02-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SellerApp', '0002_remove_tbl_tool_tool_category_and_more'),
        ('GuestApp', '0004_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentrequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_quantity', models.IntegerField()),
                ('request_tprice', models.BigIntegerField()),
                ('request_date', models.DateField()),
                ('request_requireddate', models.DateField()),
                ('request_returndate', models.DateField()),
                ('request_Remark', models.CharField(max_length=100)),
                ('request_Status', models.CharField(max_length=20)),
                ('request_toolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerApp.tbl_tool')),
                ('request_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_user')),
            ],
        ),
    ]
