# Generated by Django 4.1 on 2025-02-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('SellerApp', '0002_remove_tbl_tool_tool_category_and_more'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rentrequest',
            name='request_Remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='tbl_purchaserequest',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_quantity', models.IntegerField()),
                ('purchase_tprice', models.BigIntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_stock', models.IntegerField()),
                ('purchase_Remark', models.CharField(max_length=100, null=True)),
                ('purchase_Status', models.CharField(max_length=20)),
                ('purchase_toolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerApp.tbl_tool')),
                ('purchase_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_user')),
            ],
        ),
    ]
