# Generated by Django 4.1 on 2025-02-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_tbl_rentrequest_request_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_purchaserequest',
            name='purchase_Remark',
        ),
    ]
