# Generated by Django 4.1 on 2025-02-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('UserApp', '0003_remove_tbl_purchaserequest_purchase_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_purchaserequestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_purchaserequest')),
                ('payment_rentrequestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_rentrequest')),
                ('payment_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_user')),
            ],
        ),
    ]
