# Generated by Django 4.1 on 2025-02-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('UserApp', '0004_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchasepayment',
            fields=[
                ('ppayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppayment_amount', models.BigIntegerField()),
                ('ppayment_date', models.DateField()),
                ('ppayment_status', models.CharField(max_length=30)),
                ('ppayment_purchaserequestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_purchaserequest')),
                ('ppayment_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_user')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
