# Generated by Django 4.1 on 2025-02-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('UserApp', '0005_tbl_purchasepayment_delete_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentepayment',
            fields=[
                ('rpayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('rpayment_amount', models.BigIntegerField()),
                ('rpayment_date', models.DateField()),
                ('rpayment_status', models.CharField(max_length=30)),
                ('rpayment_rentrequestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.tbl_rentrequest')),
                ('rpayment_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_user')),
            ],
        ),
    ]
