# Generated by Django 4.1 on 2025-02-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_seller'),
        ('UserApp', '0006_tbl_rentepayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_rentepayment',
            new_name='tbl_rentpayment',
        ),
    ]
