# Generated by Django 4.1 on 2025-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_rename_tbl_rentepayment_tbl_rentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rentpayment',
            name='rpayment_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
