# Generated by Django 4.1 on 2025-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_tbl_rentpayment_rpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rentpayment',
            name='rpayment_status',
            field=models.CharField(max_length=30),
        ),
    ]
