# Generated by Django 4.1 on 2025-01-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_tbl_subcategory'),
        ('GuestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_phone', models.BigIntegerField()),
                ('user_email', models.CharField(max_length=30)),
                ('user_landmark', models.CharField(max_length=40)),
                ('user_pincode', models.BigIntegerField()),
                ('user_regdate', models.DateField()),
                ('user_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('user_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
