# Generated by Django 4.1 on 2025-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_email',
            field=models.CharField(max_length=60),
        ),
    ]
