# Generated by Django 4.1 on 2025-01-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_tbl_subcategory'),
        ('GuestApp', '0003_alter_tbl_user_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=25)),
                ('seller_image', models.ImageField(upload_to='')),
                ('seller_phone', models.BigIntegerField()),
                ('seller_email', models.CharField(max_length=60)),
                ('seller_landmark', models.CharField(max_length=40)),
                ('seller_pincode', models.BigIntegerField()),
                ('seller_idproof', models.ImageField(upload_to='')),
                ('seller_regdate', models.DateField()),
                ('seller_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('seller_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
